### ISSUE TITLE
Use a enviornment variable in the token instead of "???"

### ISSUE THREAD

**Issue by ghost** [BlueveryPi/AI_DiscordBot#1]
Just like a title.

구글 검색 해보셈 ㅋ

**Comment by BlueveryPi** [comment]
동욱아 굳이 이슈를 제기해야 했니? 곱게 알려주렴

**Comment by ghost** [comment]
ㅋㅋ

**Comment by ghost** [comment]
https://www.google.com/search?q=python+environment+variables&oq=python+&aqs=chrome.0.69i59j69i57j35i39j0i433l2j0i131i433j0i433j69i60.1099j0j1&sourceid=chrome&ie=UTF-8

**Comment by ghost** [comment]
바로 클로즈 하네 ㅋ

**Comment by ghost** [comment]
https://able.bio/rhett/how-to-set-and-get-environment-variables-in-python--274rgt
참고하라

**Comment by BlueveryPi** [comment]
ㅇㅋㄷㅋ

**Comment by BlueveryPi** [comment]
내일 봐야지

**Comment by ghost** [comment]
https://evan-moon.github.io/2019/07/25/git-tutorial/
깃도 좀 배우셈

**Comment by ghost** [comment]
이슈에서 채팅질 하는 거 ㅋㅋ

**Comment by lighton1** [comment]
난 귀여워

**Comment by ghost** [comment]
?
